---
paperclip_options:
  styles:
    slide: '950x184#'
    thumb: '200x200>'
  ## example paperclip S3 storage solution
  # storage: "s3"
  # s3_credentials: "config/s3.yml"
  # path: "site_name/:attachment/:id/:style.:extension"
  # bucket: 'bucket_name'

show_caption: false

nivo_options: #for more support visit http://nivo.dev7studios.com
  effect: "boxRainGrow" # Specify sets like: sliceDown sliceDownLeft sliceUp sliceUpLeft sliceUpDown sliceUpDownLeft fold fade random slideInRight slideInLeft boxRandom boxRain boxRainReverse boxRainGrow boxRainGrowReverse
  slices: 15 # For slice animations
  boxCols: 8 # For box animations
  boxRows: 4 # For box animations
  animSpeed: 500 # Slide transition speed
  pauseTime: 3000 # How long each slide will show
  startSlide: 0 # Set starting Slide (0 index)
  directionNav: true # Next & Prev navigation
  directionNavHide: true # Only show on hover
  controlNav: false # 1,2,3... navigation
  controlNavThumbs: false # Use thumbnails for Control Nav
  controlNavThumbsFromRel: false # Use image rel for thumbs
  controlNavThumbsSearch: '.jpg' # Replace this with...
  controlNavThumbsReplace: '_thumb.jpg' # ...this in thumb Image src
  keyboardNav: true # Use left & right arrows
  pauseOnHover: true # Stop animation while hovering
  manualAdvance: false # Force manual transitions
  captionOpacity: 0.8 # Universal caption opacity
  prevText: 'Prev' # Prev directionNav text
  nextText: 'Next' # Next directionNav text
